# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14


# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="3bf0e441-186f-4ca6-b12b-0a5437bcc697"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - azzzat72@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
